---
title: "Glosario de terminos"
format: html
editor: visual
---

## Ingresos gravados

Son todos aquellos ingresos provenientes de trabajo por relación de dependencia, actividad económica, o trabajo y capital que la Administración Tributaria reconoce para ser sujeta de impuesto de renta de régimen general.

**Los ingresos gravados de las personas naturales bajo relación de dependencia son:** remuneración mensual unificada (sueldo o salario según corresponda), sobresueldos y participación de utilidades.

## Ingresos brutos

Son todos los ingresos recibidos procedentes de cada una de las fuentes de ingresos identificadas, sean estos provenientes de la relación de dependencia, de la actividad económica empresarial o del capital y trabajo sin realizar ningún tipo de descuento.

**Para el caso de las personas naturales bajo relación de dependencia** se consideran los ingresos gravados más las décimas remuneraciones y los fondos de reserva. Este ingreso representa la capacidad económica que puede tener un individuo.
