---
title: "Glosario de terminos"
format: html
editor: visual
---

## ¿Qué es la base imponible?

En general, la base imponible está constituida por la totalidad de los ingresos ordinarios y extraordinarios gravados con el impuesto, menos las devoluciones, descuentos, costos, gastos y deducciones, imputables a tales ingresos (Asamblea Nacional del Ecuador, 2004 [última reforma 2022]).

## Base imponible de los ingresos del trabajo en relación de dependencia

La base imponible de los ingresos del trabajo en relación de dependencia está constituida por el ingreso ordinario o extraordinario que se encuentre sometido al impuesto, menos el valor de los aportes personales al IESS, excepto cuando éstos sean pagados por el empleador, sin que pueda disminuirse con rebaja o deducción alguna, excepto los gastos personales (Asamblea Nacional del Ecuador, 2004 [última reforma 2022]; Presidencia de la República del Ecuador, 2010 [última reforma 2022]).

En otras palabras, la base imponible son los ingresos gravados descontadas las aportaciones personales al IESS y los gastos personales. 

```{r echo=FALSE,message=FALSE, warning=FALSE}

library(shiny)
library(tidyverse)
library(gt)
library(shinyBS)
library(tippy)
library(scales)
library(ggrepel)
library(readxl)
library(gtExtras)
library(sparkline)
library(plotly)

basic_theme <- function(data, ...){
  data %>% 
    tab_options(
      table.background.color = "#03071e",
      ...
    )
}

read_excel("~/income_tax_calculator_table/qmd/data/franjas.xlsx") %>%
  mutate(across(everything(),.fns = as.numeric)) %>% 
    gt() %>%
    cols_label(
      fraccion_basica = "Fracción básica",
      exceso_hasta = "Exceso hasta",
      impuesto_fraccion = "Impuesto sobre la fracción básica",
      impuesto_excedente = "Impuesto sobre fracción excedente"
    )  %>%
    fmt_percent(
      columns = impuesto_excedente
    )  %>%
  fmt_currency(
      columns = c(fraccion_basica,exceso_hasta,impuesto_fraccion),
      currency = "USD"
    )  %>%
    basic_theme(
      column_labels.background.color = "#3b499c",
      row.striping.background_color = "#051052"
    ) %>% 
    opt_row_striping()  
```
