---
title: "Glosario de terminos"
format: html
editor: visual
---

## Gastos personales

Las deducciones por gastos personales son un tipo de deducciones que permiten reducir el ingreso gravable[^1] sobre el que se aplica la tasa correspondiente a alguno de los tramos de las tablas de base imponible (sección 7). De acuerdo con la normativa ecuatoriana, los contribuyentes pueden deducir sus gastos personales en seis rubros para 2022: Salud, Educación, Vestimenta, Alimentación, Vivienda, y Turismo. Los límites globales de deducciones que se pueden aplicar son:

(i) el 50% del ingreso gravable del contribuyente 
(ii) 1.3 veces la fracción básica desgravada.

**Los gastos personales deben estar sustentados en comprobantes de venta válidamente emitidos. **

Para cuantificar los gastos personales, se podrá considerar a los
realizados por los padres, cónyuge o pareja en unión de hecho e hijos
dependientes del sujeto pasivo o de su cónyuge o pareja en unión de hecho,
siempre que no perciban ingresos gravados; no obstante, en cualquier caso,
deberá excluirse el IVA e ICE de las transacciones.

## Pero ¿Que gastos me puedo deducir?

### VIVIENDA

**Arriendo:** 

Arriendo de un único inmueble usado para vivienda.

**Intereses, préstamo hipotecario:** 

Los intereses de préstamos hipotecarios otorgados por instituciones autorizadas, destinados a la ampliación, remodelación, restauración, adquisición o construcción, de una única vivienda usada para vivienda. En este caso, serán pruebas suficientes los certificados conferidos por la institución que otorgó el crédito; o el débito respectivo reflejado en los estados de cuenta o libretas de ahorro.

**Servicios básicos:**

Pagos por concepto de servicios básicos que incluyen agua, gas, electricidad, teléfono convencional y alícuota de condominio de un único inmueble usado para vivienda.

**Impuesto predial:** 

Impuestos prediales de un único bien inmueble usado para vivienda.


**Pensiones alimenticias:** 

Pensiones alimenticias, debidamente sustentadas en acta de mediación o resolución judicial.


**Otros gastos:** 

Destinados a la adquisición, construcción, remodelación,
ampliación, mejora y mantenimiento de un único bien inmueble. En todos los casos
señalados en este rubro y en los anteriores, los gastos serán considerados en
razón de una sola vivienda.

***


### EDUCACIÓN, ARTE Y CULTURA

**Matrícula y pensión:** 

Matrícula y pensión en todos los niveles del sistema educativo, inicial, educación general básica, bachillerato y superior, así como la colegiatura, los cursos de actualización, seminarios de formación profesional debidamente aprobados por el Ministerio de Educación o del Trabajo cuando corresponda o por el Consejo Nacional de Educación Superior según el caso.

* Transporte escolar.
* Derechos de grado.
* Pago de intereses de créditos educativos otorgados por instituciones debidamente
autorizadas.

**Útiles y textos escolares:** 

Útiles, textos escolares, equipos de computación, y materiales didácticos utilizados en la educación.

**Educación para personas con discapacidad:** 

Servicios de educación especial para personas con discapacidad, brindados por centros y por profesionales reconocidos por los órganos competentes.

**Cuidado y/o desarrollo infantil:** 

Servicios prestados por centros de cuidado y/o desarrollo infantil y material didáctico para el desarrollo infantil.

**Uniformes:** 

Uniformes.

**Artes vivas y escénicas:** 

Danza, teatro, ópera, mimo, artes circenses, magia, performance, títeres y video danza.

**Artes plásticas, visuales y aplicadas:** 

Dibujo, pintura, escultura, restauración, grabado, cerámica, tatuaje no cosmético, mural, fotografía, video-arte e instalaciones, alfarería, serigrafía, tallado e ilustración.

**Artes literarias y narrativas:** 

Formación e instrucción en estas áreas, pago por recitales, espectáculos y eventos en vivo vinculados con ellas, así como los pagos por adquisición de libros y revistas.

**Artes cinematográficas y audiovisuales:** 

Formación e instrucción en estas áreas, pago por concepto de exhibiciones, espectáculos y eventos audiovisuales y cinematográficos.

**Artes musicales y sonoras:** 

Formación e instrucción en estas áreas, pago por conciertos, recitales, musicales y otro tipo de eventos y espectáculos musicales en vivo, así como los pagos por adquisición de instrumentos y complementos musicales y accesorios para tales instrumentos.

**Promoción y difusión de la memoria social y el patrimonio:** 

Formación e instrucción en estas áreas, pagos por los consumos de entradas y servicios de los repositorios de memoria (museo, archivo y biblioteca).

**Artesanías:** 

Adquisición de artesanías elaboradas a mano por artesanos calificados por los organismos competentes.

**Pensiones alimenticias:** 

Pensiones alimenticias, debidamente sustentadas en acta de mediación o resolución judicial.

***

### SALUD

**Honorarios profesionales de salud:** 

Honorarios de médicos y profesionales de la salud
con título profesional avalado por el Consejo Nacional de Educación Superior.

**Servicios de salud:** 

Servicios de salud prestados por clínicas, hospitales, laboratorios y farmacias, autorizados.

**Medicinas y otros:** 

Medicamentos, insumos médicos, lentes, órtesis, prótesis y otros accesorios para la salud.

**Medicina prepagada y prima de seguro médico:** 

Medicina prepagada y prima de seguro médico en contratos individuales y corporativos. En los casos que estos valores correspondan a una póliza corporativa y los mismos sean descontados del rol de pagos del contribuyente, este documento será válido para sustentar el gasto correspondiente.

**Deducible del seguro:** 

El deducible no reembolsado de la liquidación del seguro privado.

**Pensiones alimenticias:** 

Pensiones alimenticias, debidamente sustentadas en acta de mediación o resolución judicial.

**Otros gastos:** 

Relacionados para el bienestar físico y mental, así como aquellos destinados a la prevención, recuperación y rehabilitación de la salud.

***

### ALIMENTACIÓN

**Alimentos:** 

Compras de alimentos para consumo humano y otros productos naturales o artificiales que el ser humano ingiere para subsistir o para su nutrición.

**Pensiones alimenticias:** 

Pensiones alimenticias, debidamente sustentadas en acta de mediación o resolución judicial.

**Restaurantes:** 

Compra de alimentos en centros de expendio de alimentos preparados.

***

### VESTIMENTA


**Prendas de vestir:**

Se considerarán gastos de vestimenta los realizados por cualquier tipo de prenda de vestir.

**Pensiones alimenticias:** 

Pensiones alimenticias, debidamente sustentadas en acta de mediación o resolución judicial.

***

### TURISMO

**Alojamiento:** 

Se considerarán los gastos de alojamiento turístico dentro del territorio ecuatoriano en todas sus modalidades.

**Transporte:** 

Transporte de pasajeros, incluye transporte aéreo, marítimo, fluvial, terrestre y alquiler de vehículos contratados o utilizados para turismo interno dentro de territorio ecuatoriano.

**Servicio de alimentos y bebidas:** 

Se considerarán los servicios gastronómicos en restaurantes, bares y similares, donde se expendan alimentos y/o bebidas no alcohólicas para consumo humano, adquiridos por las personas naturales durante sus actividades turísticas dentro de territorio ecuatoriano.

**Operación turística:** 

Paquetes, tours, y demás servicios turísticos prestados por operadores turísticos dentro de territorio ecuatoriano.

**Intermediación turística:** 

Agencias de servicios de turismo; organización de eventos, congresos y convenciones, dentro de territorio ecuatoriano.

**Parques de atracciones:** 

Se considerarán parques de atracciones estables dentro de territorio ecuatoriano.

**Pensiones alimenticias:** 

Pensiones alimenticias, debidamente sustentadas en acta de mediación o resolución judicial.

[^1]: Ingresos brutos
