---
title: "Glosario de terminos"
format: html
editor: visual
---

## What is the taxable income?

In general, the taxable base consists of all ordinary and extraordinary income subject to tax, less refunds, discounts, costs, expenses and deductions attributable to such income (National Assembly of Ecuador, 2004 \[last amendment 2022\]).

## Taxable income from employment in a relationship of dependency

The taxable base of income from employment as an employee is constituted by the ordinary or extraordinary income subject to tax, minus the value of personal contributions to the IESS, except when these are paid by the employer, and may not be reduced by any rebate or deduction, except for personal expenses (National Assembly of Ecuador, 2004 \[last amendment 2022\]; Presidency of the Republic of Ecuador, 2010 \[last amendment 2022\]).

In other words, the taxable income is taxable income minus personal contributions to the IESS and personal expenses.

```{r echo=FALSE,message=FALSE, warning=FALSE}

library(shiny)
library(tidyverse)
library(gt)
library(shinyBS)
library(tippy)
library(scales)
library(ggrepel)
library(readxl)
library(gtExtras)
library(sparkline)
library(plotly)

basic_theme <- function(data, ...){
  data %>% 
    tab_options(
      table.background.color = "#03071e",
      ...
    )
}

read_excel("~/income_tax_calculator_table/qmd/data/franjas.xlsx") %>%
  mutate(across(everything(),.fns = as.numeric)) %>% 
    gt() %>%
    cols_label(
      fraccion_basica = "Basic fraction",
      exceso_hasta = "Excess up",
      impuesto_fraccion = "Tax on the basic fraction",
      impuesto_excedente = "Tax on surplus fraction"
    )  %>%
    fmt_percent(
      columns = impuesto_excedente
    )  %>%
  fmt_currency(
      columns = c(fraccion_basica,exceso_hasta,impuesto_fraccion),
      currency = "USD"
    )  %>%
    basic_theme(
      column_labels.background.color = "#3b499c",
      row.striping.background_color = "#051052"
    ) %>% 
    opt_row_striping()  
```
